### ISSUE TITLE
Broken packages -- please disable/mark

### ISSUE THREAD

**Issue by zerothi** [conda-forge/sisl-feedstock#5]
Issue:

<br/>
The windows packages are all broken.

<br/>

Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

The windows packages:
```bash
win-32/sisl-0.9.2-py27_1.tar.bz2
win-64/sisl-0.9.2-py27_1.tar.bz2
```
are both broken and I would like to mark them broken.

**Comment by ocefpaf** [comment]
Done. Can you check if I got the right ones?

**Comment by zerothi** [comment]
@ocefpaf, thanks! Perfect!
